---
name: hs-dbus-signature CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  development_environment_checks:
    strategy:
      matrix:
        include:
          - dependencies: ruff
            task: make -f Makefile fmt-travis
          - dependencies: >
              libatomic
              python-hypothesis
              python3-setuptools
              ruff
            task: PATH=${PATH}:/github/home/.local/bin make -f Makefile lint
          - dependencies: python-hypothesis python3-setuptools
            task: PYTHONPATH=./src make -f Makefile test
          - dependencies: >
              python-coverage
              python-hypothesis
              python3-setuptools
            task: PYTHONPATH=./src make -f Makefile coverage
          - dependencies: python python3-build twine
            task: PYTHONPATH=./src make -f Makefile package
    runs-on: ubuntu-latest
    container: fedora:43  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install dependencies
        run: >
          dnf install -y
          make
          pip
          ${{ matrix.dependencies }}
      - name: Install pyright
        run: pip install --user pyright
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}

  general_checks:
    uses: stratis-storage/github-actions/.github/workflows/reusable_general.yml@master
    with:
      fedora-container-image-number: 43  # CURRENT DEVELOPMENT ENVIRONMENT
